In [1]:
from rdkit import Chem

In [2]:
import pandas as pd

In [3]:
import pandas as pd
df = pd.read_csv("ache sir.csv")
df.head()

,Molecule ChEMBL ID,Smiles,pChEMBL Value,Activity
0,CHEMBL64011,CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...,7.22,Active
1,CHEMBL4283770,CN(C)CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1,6.18,Active
2,CHEMBL4283733,CCN(CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1)Cc1ccccc1,4.65,Inactive
3,CHEMBL286990,C[n+]1ccn(COCC(C)(C)[N+](=O)[O-])c1/C=N/O.[Cl-],4.97,Inactive
4,CHEMBL1651046,C[C@@H]([C@H]1[C@H](O)C[C@@]2(C)[C@@H]3CC[C@@H...,4.53,Inactive

In [4]:
print(df[["Molecule ChEMBL ID", "Smiles"]].head())

  Molecule ChEMBL ID                                             Smiles
0        CHEMBL64011  CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...
1      CHEMBL4283770             CN(C)CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1
2      CHEMBL4283733    CCN(CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1)Cc1ccccc1
3       CHEMBL286990    C[n+]1ccn(COCC(C)(C)[N+](=O)[O-])c1/C=N/O.[Cl-]
4      CHEMBL1651046  C[C@@H]([C@H]1[C@H](O)C[C@@]2(C)[C@@H]3CC[C@@H...

In [7]:
from rdkit import Chem
import pandas as pd
df = pd.read_csv("ache sir.csv")
df.columns = df.columns.str.strip()
def canonicalize_smiles(smi):
    mol = Chem.MolFromSmiles(smi)
    if mol:
        return Chem.MolToSmiles(mol, canonical=True)
    else:
        return None
df["canonical_smiles"] = df["Smiles"].apply(canonicalize_smiles)
df.to_csv("canonical_smiles_outputache sir.csv", index=False)
print(df.head())

  Molecule ChEMBL ID                                             Smiles  \
0        CHEMBL64011  CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...
1      CHEMBL4283770             CN(C)CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1
2      CHEMBL4283733    CCN(CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1)Cc1ccccc1
3       CHEMBL286990    C[n+]1ccn(COCC(C)(C)[N+](=O)[O-])c1/C=N/O.[Cl-]
4      CHEMBL1651046  C[C@@H]([C@H]1[C@H](O)C[C@@]2(C)[C@@H]3CC[C@@H...

   pChEMBL Value  Activity                                   canonical_smiles
0           7.22    Active  CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...
1           6.18    Active             CN(C)CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1
2           4.65  Inactive    CCN(CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1)Cc1ccccc1
3           4.97  Inactive    C[n+]1ccn(COCC(C)(C)[N+](=O)[O-])c1/C=N/O.[Cl-]
4           4.53  Inactive  C[C@@H]([C@H]1[C@H](O)C[C@@]2(C)[C@@H]3CC[C@@H...

In [8]:
from rdkit import Chem
from rdkit.Chem import Descriptors, rdMolDescriptors
import pandas as pd
import numpy as np
def calculate_descriptors(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return pd.Series({
            "MolWt": np.nan,
            "LogP": np.nan,
            "H_Donors": np.nan,
            "H_Acceptors": np.nan,
            "TPSA": np.nan,
            "NumRotatableBonds": np.nan,

            "NumAtoms": np.nan,
            "HeavyAtomCount": np.nan,
            "NumHeteroatoms": np.nan,
            "NumCarbons": np.nan,
            "NumNitrogens": np.nan,
            "NumOxygens": np.nan,
            "NumHalogens": np.nan,

            "NumBonds": np.nan,
            "NumDoubleBonds": np.nan,
            "NumTripleBonds": np.nan,

            "NumRings": np.nan,
            "NumAromaticRings": np.nan,
            "NumAliphaticRings": np.nan,
            "NumSaturatedRings": np.nan,

            "NumAromaticAtoms": np.nan,
            "NumAliphaticAtoms": np.nan,

            "FractionCSP3": np.nan
        })

    MolWt = Descriptors.MolWt(mol)

    LogP = Descriptors.MolLogP(mol)

    H_Donors = Descriptors.NumHDonors(mol)

    H_Acceptors = Descriptors.NumHAcceptors(mol)

    TPSA = Descriptors.TPSA(mol)

    NumRotatableBonds = Descriptors.NumRotatableBonds(mol)

    NumAtoms = mol.GetNumAtoms()

    HeavyAtomCount = mol.GetNumHeavyAtoms()


    # Count heteroatoms
    NumHeteroatoms = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetAtomicNum() not in [1, 6]
    )


    # Carbon atoms
    NumCarbons = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetAtomicNum() == 6
    )


    # Nitrogen atoms
    NumNitrogens = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetAtomicNum() == 7
    )


    # Oxygen atoms
    NumOxygens = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetAtomicNum() == 8
    )


    # Halogen atoms: F, Cl, Br, I
    NumHalogens = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetAtomicNum() in [9, 17, 35, 53]
    )


    # ========================================================
    # 3. BOND COUNTS
    # ========================================================

    NumBonds = mol.GetNumBonds()


    NumDoubleBonds = sum(
        1 for bond in mol.GetBonds()
        if bond.GetBondType() == Chem.BondType.DOUBLE
    )


    NumTripleBonds = sum(
        1 for bond in mol.GetBonds()
        if bond.GetBondType() == Chem.BondType.TRIPLE
    )

    NumRings = rdMolDescriptors.CalcNumRings(mol)

    NumAromaticRings = rdMolDescriptors.CalcNumAromaticRings(mol)

    NumAliphaticRings = rdMolDescriptors.CalcNumAliphaticRings(mol)

    NumSaturatedRings = rdMolDescriptors.CalcNumSaturatedRings(mol)

    NumAromaticAtoms = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetIsAromatic()
    )


    NumAliphaticAtoms = sum(
        1 for atom in mol.GetAtoms()
        if not atom.GetIsAromatic()
    )


    FractionCSP3 = rdMolDescriptors.CalcFractionCSP3(mol)



    return pd.Series({

        # Lipinski
        "MolWt": MolWt,
        "LogP": LogP,
        "H_Donors": H_Donors,
        "H_Acceptors": H_Acceptors,
    "TPSA": TPSA,
        "NumRotatableBonds": NumRotatableBonds,

        # Atom counts
        "NumAtoms": NumAtoms,
        "HeavyAtomCount": HeavyAtomCount,
        "NumHeteroatoms": NumHeteroatoms,
        "NumCarbons": NumCarbons,
        "NumNitrogens": NumNitrogens,
        "NumOxygens": NumOxygens,
        "NumHalogens": NumHalogens,

        # Bond counts
        "NumBonds": NumBonds,
        "NumDoubleBonds": NumDoubleBonds,
        "NumTripleBonds": NumTripleBonds,

        # Ring counts
        "NumRings": NumRings,
        "NumAromaticRings": NumAromaticRings,
        "NumAliphaticRings": NumAliphaticRings,
        "NumSaturatedRings": NumSaturatedRings,

        # Aromaticity
        "NumAromaticAtoms": NumAromaticAtoms,
        "NumAliphaticAtoms": NumAliphaticAtoms,

        # Carbon hybridization
        "FractionCSP3": FractionCSP3
    })

descriptor_columns = [
    "MolWt",
    "LogP",
    "H_Donors",
    "H_Acceptors",
    "TPSA",
    "NumRotatableBonds",

    "NumAtoms",
    "HeavyAtomCount",
    "NumHeteroatoms",
    "NumCarbons",
    "NumNitrogens",
    "NumOxygens",
    "NumHalogens",

    "NumBonds",
    "NumDoubleBonds",
    "NumTripleBonds",

    "NumRings",
    "NumAromaticRings",
    "NumAliphaticRings",
    "NumSaturatedRings",

    "NumAromaticAtoms",
    "NumAliphaticAtoms",

    "FractionCSP3"
]


df[descriptor_columns] = df["canonical_smiles"].apply(
    calculate_descriptors
)

df.to_csv(
    "ache sir_descriptors.csv",
    index=False
)
print("Descriptor calculation completed successfully!")

print("\nNumber of descriptors generated:",
      len(descriptor_columns))

print("\nDescriptor columns:")
print(descriptor_columns)

print("\nFirst 5 rows:")
display(df[descriptor_columns].head())

print("\nFinal dataset shape:")
print(df.shape)

Descriptor calculation completed successfully!

Number of descriptors generated: 23

Descriptor columns:
['MolWt', 'LogP', 'H_Donors', 'H_Acceptors', 'TPSA', 'NumRotatableBonds', 'NumAtoms', 'HeavyAtomCount', 'NumHeteroatoms', 'NumCarbons', 'NumNitrogens', 'NumOxygens', 'NumHalogens', 'NumBonds', 'NumDoubleBonds', 'NumTripleBonds', 'NumRings', 'NumAromaticRings', 'NumAliphaticRings', 'NumSaturatedRings', 'NumAromaticAtoms', 'NumAliphaticAtoms', 'FractionCSP3']

First 5 rows:

,MolWt,LogP,H_Donors,H_Acceptors,TPSA,NumRotatableBonds,NumAtoms,HeavyAtomCount,NumHeteroatoms,NumCarbons,...,NumBonds,NumDoubleBonds,NumTripleBonds,NumRings,NumAromaticRings,NumAliphaticRings,NumSaturatedRings,NumAromaticAtoms,NumAliphaticAtoms,FractionCSP3
0,472.674,4.2070,1.0,6.0,57.28,11.0,34.0,34.0,7.0,27.0,...,37.0,1.0,0.0,4.0,1.0,3.0,2.0,6.0,28.0,0.740741
1,323.392,3.2857,0.0,4.0,38.77,5.0,24.0,24.0,4.0,20.0,...,26.0,2.0,0.0,3.0,2.0,1.0,0.0,12.0,12.0,0.250000
2,413.517,5.2462,0.0,4.0,38.77,8.0,31.0,31.0,4.0,27.0,...,34.0,2.0,0.0,4.0,3.0,1.0,0.0,18.0,13.0,0.222222
3,292.723,-2.8459,1.0,5.0,93.77,6.0,19.0,19.0,9.0,10.0,...,18.0,2.0,0.0,1.0,1.0,0.0,0.0,5.0,14.0,0.600000
4,428.705,5.3628,1.0,3.0,26.71,3.0,31.0,31.0,3.0,28.0,...,34.0,2.0,0.0,4.0,0.0,4.0,2.0,0.0,31.0,0.857143

Final dataset shape:
(5743, 28)

In [9]:
df_smiles = pd.read_csv("canonical_smiles_outputache sir.csv")
print(df_smiles.columns)

Index(['Molecule ChEMBL ID', 'Smiles', 'pChEMBL Value', 'Activity',
       'canonical_smiles'],
      dtype='str')

In [15]:
df_desc = pd.read_csv("ache sir_descriptors.csv")
df_smiles = pd.read_csv("canonical_smiles_outputache sir.csv")

df_desc["canonical_smiles"] = df_smiles["canonical_smiles"]

df_desc.to_csv("final_with_descriptorsache sir_updated.csv", index=False)

print("✅ canonical_smiles added successfully")
print(df_desc.head())

✅ canonical_smiles added successfully
  Molecule ChEMBL ID                                             Smiles  \
0        CHEMBL64011  CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...
1      CHEMBL4283770             CN(C)CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1
2      CHEMBL4283733    CCN(CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1)Cc1ccccc1
3       CHEMBL286990    C[n+]1ccn(COCC(C)(C)[N+](=O)[O-])c1/C=N/O.[Cl-]
4      CHEMBL1651046  C[C@@H]([C@H]1[C@H](O)C[C@@]2(C)[C@@H]3CC[C@@H...

   pChEMBL Value  Activity                                   canonical_smiles  \
0           7.22    Active  CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...
1           6.18    Active             CN(C)CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1
2           4.65  Inactive    CCN(CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1)Cc1ccccc1
3           4.97  Inactive    C[n+]1ccn(COCC(C)(C)[N+](=O)[O-])c1/C=N/O.[Cl-]
4           4.53  Inactive  C[C@@H]([C@H]1[C@H](O)C[C@@]2(C)[C@@H]3CC[C@@H...

     MolWt    LogP  H_Donors  H_Acceptors   TPSA  ...  NumBonds  \
0  472.674  4.2070       1.0          6.0  57.28  ...      37.0
1  323.392  3.2857       0.0          4.0  38.77  ...      26.0
2  413.517  5.2462       0.0          4.0  38.77  ...      34.0
3  292.723 -2.8459       1.0          5.0  93.77  ...      18.0
4  428.705  5.3628       1.0          3.0  26.71  ...      34.0

   NumDoubleBonds  NumTripleBonds  NumRings  NumAromaticRings  \
0             1.0             0.0       4.0               1.0
1             2.0             0.0       3.0               2.0
2             2.0             0.0       4.0               3.0
3             2.0             0.0       1.0               1.0
4             2.0             0.0       4.0               0.0

   NumAliphaticRings  NumSaturatedRings  NumAromaticAtoms  NumAliphaticAtoms  \
0                3.0                2.0               6.0               28.0
1                1.0                0.0              12.0               12.0
2                1.0                0.0              18.0               13.0
3                0.0                0.0               5.0               14.0
4                4.0                2.0               0.0               31.0

   FractionCSP3
0      0.740741
1      0.250000
2      0.222222
3      0.600000
4      0.857143

[5 rows x 28 columns]

In [16]:
from rdkit import Chem
from rdkit.Chem import MACCSkeys
import pandas as pd
import numpy as np
df = pd.read_csv("final_with_descriptorsache sir_updated.csv")

# Function
def maccs_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return np.array(MACCSkeys.GenMACCSKeys(mol))
    else:
        return np.zeros(167)

# Apply
maccs = df["canonical_smiles"].apply(maccs_fp)

# Convert to DataFrame
maccs_df = pd.DataFrame(maccs.tolist())
maccs_df.columns = [f"maccs_{i}" for i in range(maccs_df.shape[1])]

# Add to main dataset
df = pd.concat([df, maccs_df], axis=1)

# Save
df.to_csv("step1_maccs_addedache sir.csv", index=False)

print("✅ MACCS done")
print(df.shape)

✅ MACCS done
(5743, 195)

In [17]:
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
import pandas as pd
import numpy as np

# Load your dataset (must contain canonical_smiles)
df = pd.read_csv("final_with_descriptorsache sir_updated.csv")

# Initialize Morgan generator (NEW method)
morgan_gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)

# Function to generate fingerprint
def morgan_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return np.array(morgan_gen.GetFingerprint(mol))
    else:
        return np.zeros(2048)

# Apply on canonical_smiles column
morgan = df["canonical_smiles"].apply(morgan_fp)

# Convert to DataFrame
morgan_df = pd.DataFrame(morgan.tolist())

# Rename columns
morgan_df.columns = [f"morgan_{i}" for i in range(morgan_df.shape[1])]

# Combine with original dataset
df_final = pd.concat([df, morgan_df], axis=1)
# Save output
df_final.to_csv("morgan_addedache sir.csv", index=False)

print("✅ Morgan fingerprint added successfully")
print("Shape:", df_final.shape)
print(df_final.head())

✅ Morgan fingerprint added successfully
Shape: (5743, 2076)
  Molecule ChEMBL ID                                             Smiles  \
0        CHEMBL64011  CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...
1      CHEMBL4283770             CN(C)CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1
2      CHEMBL4283733    CCN(CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1)Cc1ccccc1
3       CHEMBL286990    C[n+]1ccn(COCC(C)(C)[N+](=O)[O-])c1/C=N/O.[Cl-]
4      CHEMBL1651046  C[C@@H]([C@H]1[C@H](O)C[C@@]2(C)[C@@H]3CC[C@@H...

   pChEMBL Value  Activity                                   canonical_smiles  \
0           7.22    Active  CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...
1           6.18    Active             CN(C)CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1
2           4.65  Inactive    CCN(CCOc1ccc(/C=C2\COc3ccccc3C2=O)cc1)Cc1ccccc1
3           4.97  Inactive    C[n+]1ccn(COCC(C)(C)[N+](=O)[O-])c1/C=N/O.[Cl-]
4           4.53  Inactive  C[C@@H]([C@H]1[C@H](O)C[C@@]2(C)[C@@H]3CC[C@@H...

     MolWt    LogP  H_Donors  H_Acceptors   TPSA  ...  morgan_2038  \
0  472.674  4.2070       1.0          6.0  57.28  ...            0
1  323.392  3.2857       0.0          4.0  38.77  ...            0
2  413.517  5.2462       0.0          4.0  38.77  ...            0
3  292.723 -2.8459       1.0          5.0  93.77  ...            0
4  428.705  5.3628       1.0          3.0  26.71  ...            0

   morgan_2039  morgan_2040  morgan_2041  morgan_2042  morgan_2043  \
0            0            0            0            0            0
1            0            0            0            0            0
2            0            0            0            0            0
3            0            0            0            0            0
4            0            0            0            0            0

   morgan_2044  morgan_2045  morgan_2046  morgan_2047
0            0            0            0            0
1            0            0            0            0
2            0            0            0            0
3            1            0            0            0
4            0            0            0            0

[5 rows x 2076 columns]

In [18]:
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
import pandas as pd
import numpy as np

# Load previous dataset (use latest file you created)
df = pd.read_csv("morgan_addedache sir.csv")   # or your latest file

# Initialize AtomPair generator
ap_gen = rdFingerprintGenerator.GetAtomPairGenerator(fpSize=1024)

# Function
def atompair_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return np.array(ap_gen.GetFingerprint(mol))
    else:
        return np.zeros(1024)

# Apply
ap = df["canonical_smiles"].apply(atompair_fp)

# Convert to DataFrame
ap_df = pd.DataFrame(ap.tolist())

# Rename columns
ap_df.columns = [f"atompair_{i}" for i in range(ap_df.shape[1])]
# Combine with dataset
df_final = pd.concat([df, ap_df], axis=1)

# Save
df_final.to_csv("atompair_addedache sir.csv", index=False)
print("✅ AtomPair fingerprint added")
print("Shape:", df_final.shape)

✅ AtomPair fingerprint added
Shape: (5743, 3100)

In [19]:
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
import pandas as pd
import numpy as np
df = pd.read_csv("atompair_addedache sir.csv")
rdk_gen = rdFingerprintGenerator.GetRDKitFPGenerator(fpSize=2048)
def rdk_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return np.array(rdk_gen.GetFingerprint(mol))
    else:
        return np.zeros(2048)
rdk = df["canonical_smiles"].apply(rdk_fp)
rdk_df = pd.DataFrame(rdk.tolist())
rdk_df.columns = [f"rdk_{i}" for i in range(rdk_df.shape[1])]
df_final = pd.concat([df, rdk_df], axis=1)
df_final.to_csv("final_full_datasetache sir.csv", index=False)
print("✅ RDK fingerprint added — FINAL DATASET READY")
print("Shape:", df_final.shape)

✅ RDK fingerprint added — FINAL DATASET READY
Shape: (5743, 5148)