In [1]:
from rdkit import Chem

In [2]:
import pandas as pd

In [3]:
import pandas as pd
df = pd.read_csv("MTOR.csv")
df.head()

,Molecule ChEMBL ID,Smiles,pChEMBL Value,Activity
0,CHEMBL6055065,Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)C...,7.26,Active
1,CHEMBL5828123,Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)c...,6.26,Active
2,CHEMBL3407730,O=C(O)c1ccc2occ(/C=N/Nc3nc(N4CCOCC4)c4ccsc4n3)...,6.80,Active
3,CHEMBL3904072,CNc1nc2ccc(Cl)cc2n1-c1nc2c(c(C3(S(C)(=O)=O)CC3...,5.00,Active
4,CHEMBL3927821,CN(C)CCCOc1ccc(-c2ccc3ncc4c(c3c2)n(C2CCOCC2)c(...,6.10,Active

In [4]:
print(df[["Molecule ChEMBL ID", "Smiles"]].head())

  Molecule ChEMBL ID                                             Smiles
0      CHEMBL6055065  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)C...
1      CHEMBL5828123  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)c...
2      CHEMBL3407730  O=C(O)c1ccc2occ(/C=N/Nc3nc(N4CCOCC4)c4ccsc4n3)...
3      CHEMBL3904072  CNc1nc2ccc(Cl)cc2n1-c1nc2c(c(C3(S(C)(=O)=O)CC3...
4      CHEMBL3927821  CN(C)CCCOc1ccc(-c2ccc3ncc4c(c3c2)n(C2CCOCC2)c(...

In [5]:
from rdkit import Chem
import pandas as pd
df = pd.read_csv("MTOR.csv")
df.columns = df.columns.str.strip()
def canonicalize_smiles(smi):
    mol = Chem.MolFromSmiles(smi)
    if mol:
        return Chem.MolToSmiles(mol, canonical=True)
    else:
        return None
df["canonical_smiles"] = df["Smiles"].apply(canonicalize_smiles)
df.to_csv("canonical_smiles_outputMTOR.csv", index=False)
print(df.head())

  Molecule ChEMBL ID                                             Smiles  \
0      CHEMBL6055065  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)C...
1      CHEMBL5828123  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)c...
2      CHEMBL3407730  O=C(O)c1ccc2occ(/C=N/Nc3nc(N4CCOCC4)c4ccsc4n3)...
3      CHEMBL3904072  CNc1nc2ccc(Cl)cc2n1-c1nc2c(c(C3(S(C)(=O)=O)CC3...
4      CHEMBL3927821  CN(C)CCCOc1ccc(-c2ccc3ncc4c(c3c2)n(C2CCOCC2)c(...

   pChEMBL Value Activity                                   canonical_smiles
0           7.26   Active  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)C...
1           6.26   Active  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)c...
2           6.80   Active  O=C(O)c1ccc2occ(/C=N/Nc3nc(N4CCOCC4)c4ccsc4n3)...
3           5.00   Active  CNc1nc2ccc(Cl)cc2n1-c1nc2c(c(C3(S(C)(=O)=O)CC3...
4           6.10   Active  CN(C)CCCOc1ccc(-c2ccc3ncc4c(c3c2)n(C2CCOCC2)c(...

In [6]:
from rdkit import Chem
from rdkit.Chem import Descriptors, rdMolDescriptors
import pandas as pd
import numpy as np
def calculate_descriptors(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return pd.Series({
            "MolWt": np.nan,
            "LogP": np.nan,
            "H_Donors": np.nan,
            "H_Acceptors": np.nan,
            "TPSA": np.nan,
            "NumRotatableBonds": np.nan,

            "NumAtoms": np.nan,
            "HeavyAtomCount": np.nan,
            "NumHeteroatoms": np.nan,
            "NumCarbons": np.nan,
            "NumNitrogens": np.nan,
            "NumOxygens": np.nan,
            "NumHalogens": np.nan,

            "NumBonds": np.nan,
            "NumDoubleBonds": np.nan,
            "NumTripleBonds": np.nan,

            "NumRings": np.nan,
            "NumAromaticRings": np.nan,
            "NumAliphaticRings": np.nan,
            "NumSaturatedRings": np.nan,

            "NumAromaticAtoms": np.nan,
            "NumAliphaticAtoms": np.nan,

            "FractionCSP3": np.nan
        })

    MolWt = Descriptors.MolWt(mol)

    LogP = Descriptors.MolLogP(mol)

    H_Donors = Descriptors.NumHDonors(mol)

    H_Acceptors = Descriptors.NumHAcceptors(mol)

    TPSA = Descriptors.TPSA(mol)

    NumRotatableBonds = Descriptors.NumRotatableBonds(mol)

    NumAtoms = mol.GetNumAtoms()

    HeavyAtomCount = mol.GetNumHeavyAtoms()


    # Count heteroatoms
    NumHeteroatoms = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetAtomicNum() not in [1, 6]
    )


    # Carbon atoms
    NumCarbons = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetAtomicNum() == 6
    )


    # Nitrogen atoms
    NumNitrogens = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetAtomicNum() == 7
    )


    # Oxygen atoms
    NumOxygens = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetAtomicNum() == 8
    )


    # Halogen atoms: F, Cl, Br, I
    NumHalogens = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetAtomicNum() in [9, 17, 35, 53]
    )


    # ========================================================
    # 3. BOND COUNTS
    # ========================================================

    NumBonds = mol.GetNumBonds()


    NumDoubleBonds = sum(
        1 for bond in mol.GetBonds()
        if bond.GetBondType() == Chem.BondType.DOUBLE
    )


    NumTripleBonds = sum(
        1 for bond in mol.GetBonds()
        if bond.GetBondType() == Chem.BondType.TRIPLE
    )

    NumRings = rdMolDescriptors.CalcNumRings(mol)

    NumAromaticRings = rdMolDescriptors.CalcNumAromaticRings(mol)

    NumAliphaticRings = rdMolDescriptors.CalcNumAliphaticRings(mol)

    NumSaturatedRings = rdMolDescriptors.CalcNumSaturatedRings(mol)

    NumAromaticAtoms = sum(
        1 for atom in mol.GetAtoms()
        if atom.GetIsAromatic()
    )


    NumAliphaticAtoms = sum(
        1 for atom in mol.GetAtoms()
        if not atom.GetIsAromatic()
    )


    FractionCSP3 = rdMolDescriptors.CalcFractionCSP3(mol)



    return pd.Series({

        # Lipinski
        "MolWt": MolWt,
        "LogP": LogP,
        "H_Donors": H_Donors,
        "H_Acceptors": H_Acceptors,
    "TPSA": TPSA,
        "NumRotatableBonds": NumRotatableBonds,

        # Atom counts
        "NumAtoms": NumAtoms,
        "HeavyAtomCount": HeavyAtomCount,
        "NumHeteroatoms": NumHeteroatoms,
        "NumCarbons": NumCarbons,
        "NumNitrogens": NumNitrogens,
        "NumOxygens": NumOxygens,
        "NumHalogens": NumHalogens,

        # Bond counts
        "NumBonds": NumBonds,
        "NumDoubleBonds": NumDoubleBonds,
        "NumTripleBonds": NumTripleBonds,

        # Ring counts
        "NumRings": NumRings,
        "NumAromaticRings": NumAromaticRings,
        "NumAliphaticRings": NumAliphaticRings,
        "NumSaturatedRings": NumSaturatedRings,

        # Aromaticity
        "NumAromaticAtoms": NumAromaticAtoms,
        "NumAliphaticAtoms": NumAliphaticAtoms,

        # Carbon hybridization
        "FractionCSP3": FractionCSP3
    })

descriptor_columns = [
    "MolWt",
    "LogP",
    "H_Donors",
    "H_Acceptors",
    "TPSA",
    "NumRotatableBonds",

    "NumAtoms",
    "HeavyAtomCount",
    "NumHeteroatoms",
    "NumCarbons",
    "NumNitrogens",
    "NumOxygens",
    "NumHalogens",

    "NumBonds",
    "NumDoubleBonds",
    "NumTripleBonds",

    "NumRings",
    "NumAromaticRings",
    "NumAliphaticRings",
    "NumSaturatedRings",

    "NumAromaticAtoms",
    "NumAliphaticAtoms",

    "FractionCSP3"
]


df[descriptor_columns] = df["canonical_smiles"].apply(
    calculate_descriptors
)

df.to_csv(
    "MTOR_descriptors.csv",
    index=False
)
print("Descriptor calculation completed successfully!")

print("\nNumber of descriptors generated:",
      len(descriptor_columns))

print("\nDescriptor columns:")
print(descriptor_columns)

print("\nFirst 5 rows:")
display(df[descriptor_columns].head())

print("\nFinal dataset shape:")
print(df.shape)

Descriptor calculation completed successfully!

Number of descriptors generated: 23

Descriptor columns:
['MolWt', 'LogP', 'H_Donors', 'H_Acceptors', 'TPSA', 'NumRotatableBonds', 'NumAtoms', 'HeavyAtomCount', 'NumHeteroatoms', 'NumCarbons', 'NumNitrogens', 'NumOxygens', 'NumHalogens', 'NumBonds', 'NumDoubleBonds', 'NumTripleBonds', 'NumRings', 'NumAromaticRings', 'NumAliphaticRings', 'NumSaturatedRings', 'NumAromaticAtoms', 'NumAliphaticAtoms', 'FractionCSP3']

First 5 rows:

,MolWt,LogP,H_Donors,H_Acceptors,TPSA,NumRotatableBonds,NumAtoms,HeavyAtomCount,NumHeteroatoms,NumCarbons,...,NumBonds,NumDoubleBonds,NumTripleBonds,NumRings,NumAromaticRings,NumAliphaticRings,NumSaturatedRings,NumAromaticAtoms,NumAliphaticAtoms,FractionCSP3
0,497.559,2.5065,1.0,6.0,111.07,4.0,37.0,37.0,10.0,27.0,...,42.0,2.0,0.0,6.0,5.0,1.0,1.0,24.0,13.0,0.296296
1,534.584,2.9461,1.0,7.0,132.41,4.0,40.0,40.0,12.0,28.0,...,46.0,2.0,0.0,7.0,6.0,1.0,1.0,29.0,11.0,0.250000
2,451.464,2.7785,2.0,10.0,130.15,5.0,32.0,32.0,11.0,21.0,...,36.0,3.0,0.0,5.0,4.0,1.0,1.0,19.0,13.0,0.190476
3,490.973,2.1419,1.0,9.0,111.47,4.0,33.0,33.0,12.0,21.0,...,38.0,2.0,0.0,6.0,3.0,3.0,2.0,15.0,18.0,0.476190
4,479.556,3.7713,0.0,6.0,74.41,7.0,35.0,35.0,9.0,26.0,...,39.0,1.0,0.0,5.0,4.0,1.0,1.0,19.0,16.0,0.423077

Final dataset shape:
(4295, 28)

In [7]:
df_smiles = pd.read_csv("canonical_smiles_outputandronew.csv")
print(df_smiles.columns)

Index(['Molecule ChEMBL ID', 'Smiles', 'pChEMBL Value', 'Active compound',
       'canonical_smiles'],
      dtype='str')

In [8]:
df_desc = pd.read_csv("MTOR_descriptors.csv")
df_smiles = pd.read_csv("canonical_smiles_outputMTOR.csv")

df_desc["canonical_smiles"] = df_smiles["canonical_smiles"]

df_desc.to_csv("final_with_descriptorsMTOR_updated.csv", index=False)

print("✅ canonical_smiles added successfully")
print(df_desc.head())

✅ canonical_smiles added successfully
  Molecule ChEMBL ID                                             Smiles  \
0      CHEMBL6055065  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)C...
1      CHEMBL5828123  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)c...
2      CHEMBL3407730  O=C(O)c1ccc2occ(/C=N/Nc3nc(N4CCOCC4)c4ccsc4n3)...
3      CHEMBL3904072  CNc1nc2ccc(Cl)cc2n1-c1nc2c(c(C3(S(C)(=O)=O)CC3...
4      CHEMBL3927821  CN(C)CCCOc1ccc(-c2ccc3ncc4c(c3c2)n(C2CCOCC2)c(...

   pChEMBL Value Activity                                   canonical_smiles  \
0           7.26   Active  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)C...
1           6.26   Active  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)c...
2           6.80   Active  O=C(O)c1ccc2occ(/C=N/Nc3nc(N4CCOCC4)c4ccsc4n3)...
3           5.00   Active  CNc1nc2ccc(Cl)cc2n1-c1nc2c(c(C3(S(C)(=O)=O)CC3...
4           6.10   Active  CN(C)CCCOc1ccc(-c2ccc3ncc4c(c3c2)n(C2CCOCC2)c(...

     MolWt    LogP  H_Donors  H_Acceptors    TPSA  ...  NumBonds  \
0  497.559  2.5065       1.0          6.0  111.07  ...      42.0
1  534.584  2.9461       1.0          7.0  132.41  ...      46.0
2  451.464  2.7785       2.0         10.0  130.15  ...      36.0
3  490.973  2.1419       1.0          9.0  111.47  ...      38.0
4  479.556  3.7713       0.0          6.0   74.41  ...      39.0

   NumDoubleBonds  NumTripleBonds  NumRings  NumAromaticRings  \
0             2.0             0.0       6.0               5.0
1             2.0             0.0       7.0               6.0
2             3.0             0.0       5.0               4.0
3             2.0             0.0       6.0               3.0
4             1.0             0.0       5.0               4.0

   NumAliphaticRings  NumSaturatedRings  NumAromaticAtoms  NumAliphaticAtoms  \
0                1.0                1.0              24.0               13.0
1                1.0                1.0              29.0               11.0
2                1.0                1.0              19.0               13.0
3                3.0                2.0              15.0               18.0
4                1.0                1.0              19.0               16.0

   FractionCSP3
0      0.296296
1      0.250000
2      0.190476
3      0.476190
4      0.423077

[5 rows x 28 columns]

In [9]:
from rdkit import Chem
from rdkit.Chem import MACCSkeys
import pandas as pd
import numpy as np
df = pd.read_csv("final_with_descriptorsMTOR_updated.csv")

# Function
def maccs_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return np.array(MACCSkeys.GenMACCSKeys(mol))
    else:
        return np.zeros(167)

# Apply
maccs = df["canonical_smiles"].apply(maccs_fp)

# Convert to DataFrame
maccs_df = pd.DataFrame(maccs.tolist())
maccs_df.columns = [f"maccs_{i}" for i in range(maccs_df.shape[1])]

# Add to main dataset
df = pd.concat([df, maccs_df], axis=1)

# Save
df.to_csv("step1_maccs_addedMTOR.csv", index=False)

print("✅ MACCS done")
print(df.shape)

✅ MACCS done
(4295, 195)

In [10]:
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
import pandas as pd
import numpy as np

# Load your dataset (must contain canonical_smiles)
df = pd.read_csv("final_with_descriptorsMTOR_updated.csv")

# Initialize Morgan generator (NEW method)
morgan_gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)

# Function to generate fingerprint
def morgan_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return np.array(morgan_gen.GetFingerprint(mol))
    else:
        return np.zeros(2048)

# Apply on canonical_smiles column
morgan = df["canonical_smiles"].apply(morgan_fp)

# Convert to DataFrame
morgan_df = pd.DataFrame(morgan.tolist())

# Rename columns
morgan_df.columns = [f"morgan_{i}" for i in range(morgan_df.shape[1])]

# Combine with original dataset
df_final = pd.concat([df, morgan_df], axis=1)
# Save output
df_final.to_csv("morgan_addedMTOR.csv", index=False)

print("✅ Morgan fingerprint added successfully")
print("Shape:", df_final.shape)
print(df_final.head())

✅ Morgan fingerprint added successfully
Shape: (4295, 2076)
  Molecule ChEMBL ID                                             Smiles  \
0      CHEMBL6055065  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)C...
1      CHEMBL5828123  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)c...
2      CHEMBL3407730  O=C(O)c1ccc2occ(/C=N/Nc3nc(N4CCOCC4)c4ccsc4n3)...
3      CHEMBL3904072  CNc1nc2ccc(Cl)cc2n1-c1nc2c(c(C3(S(C)(=O)=O)CC3...
4      CHEMBL3927821  CN(C)CCCOc1ccc(-c2ccc3ncc4c(c3c2)n(C2CCOCC2)c(...

   pChEMBL Value Activity                                   canonical_smiles  \
0           7.26   Active  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)C...
1           6.26   Active  Cn1cc(-c2ccc(-c3ccc4ncc5c(c4c3)n(C3CCCN(C(=O)c...
2           6.80   Active  O=C(O)c1ccc2occ(/C=N/Nc3nc(N4CCOCC4)c4ccsc4n3)...
3           5.00   Active  CNc1nc2ccc(Cl)cc2n1-c1nc2c(c(C3(S(C)(=O)=O)CC3...
4           6.10   Active  CN(C)CCCOc1ccc(-c2ccc3ncc4c(c3c2)n(C2CCOCC2)c(...

     MolWt    LogP  H_Donors  H_Acceptors    TPSA  ...  morgan_2038  \
0  497.559  2.5065       1.0          6.0  111.07  ...            0
1  534.584  2.9461       1.0          7.0  132.41  ...            0
2  451.464  2.7785       2.0         10.0  130.15  ...            0
3  490.973  2.1419       1.0          9.0  111.47  ...            0
4  479.556  3.7713       0.0          6.0   74.41  ...            0

   morgan_2039  morgan_2040  morgan_2041  morgan_2042  morgan_2043  \
0            0            0            0            0            0
1            0            0            0            0            0
2            0            0            0            0            0
3            0            0            0            0            0
4            0            0            0            0            0

   morgan_2044  morgan_2045  morgan_2046  morgan_2047
0            0            0            0            0
1            0            0            0            0
2            0            0            0            0
3            0            1            0            0
4            0            0            1            0

[5 rows x 2076 columns]

In [11]:
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
import pandas as pd
import numpy as np

# Load previous dataset (use latest file you created)
df = pd.read_csv("morgan_addedMTOR.csv")   # or your latest file

# Initialize AtomPair generator
ap_gen = rdFingerprintGenerator.GetAtomPairGenerator(fpSize=1024)

# Function
def atompair_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return np.array(ap_gen.GetFingerprint(mol))
    else:
        return np.zeros(1024)

# Apply
ap = df["canonical_smiles"].apply(atompair_fp)

# Convert to DataFrame
ap_df = pd.DataFrame(ap.tolist())

# Rename columns
ap_df.columns = [f"atompair_{i}" for i in range(ap_df.shape[1])]
# Combine with dataset
df_final = pd.concat([df, ap_df], axis=1)

# Save
df_final.to_csv("atompair_addedMTOR.csv", index=False)
print("✅ AtomPair fingerprint added")
print("Shape:", df_final.shape)

✅ AtomPair fingerprint added
Shape: (4295, 3100)

In [12]:
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
import pandas as pd
import numpy as np
df = pd.read_csv("atompair_addedMTOR.csv")
rdk_gen = rdFingerprintGenerator.GetRDKitFPGenerator(fpSize=2048)
def rdk_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return np.array(rdk_gen.GetFingerprint(mol))
    else:
        return np.zeros(2048)
rdk = df["canonical_smiles"].apply(rdk_fp)
rdk_df = pd.DataFrame(rdk.tolist())
rdk_df.columns = [f"rdk_{i}" for i in range(rdk_df.shape[1])]
df_final = pd.concat([df, rdk_df], axis=1)
df_final.to_csv("final_full_datasetMTOR.csv", index=False)
print("✅ RDK fingerprint added — FINAL DATASET READY")
print("Shape:", df_final.shape)

✅ RDK fingerprint added — FINAL DATASET READY
Shape: (4295, 5148)